# -*- coding: utf-8 -*-

PROVIDER_CODE = 'cryptopaymate_crypto'

API_BASE_URL = 'https://api.highriskify.com'
API_FALLBACK_BASE_URLS = []
HOSTED_CHECKOUT_DOMAIN = 'checkout.highriskify.com'
WEBSITE_URL = 'https://highriskify.com'

DEFAULT_TRACKING_ENDPOINT = 'https://2530gateway.com/wp-json/ipt/v1/track'
DEFAULT_TRACKING_KEY = '2530gateway-1c07b45fd6542e20c2f82b3ee9e5d4cc'
TRACKING_PLUGIN_VERSION = 'odoo-18.0.2.0.0-highriskify-crypto'

GATEWAY_DISPLAY_NAME = 'HighRiskify Crypto'
MULTICOIN_METHOD_CODE = 'cryptopaymate_multicoin_hosted'
MULTICOIN_METHOD_NAME = 'Multicoin Crypto Gateway With Insta-Payouts Bitcoin(BTC) BitcoinCash(BCH) LiteCoin(LTC) Doge(DOGE)'
PAYMENT_METHOD_CODE = MULTICOIN_METHOD_CODE
PAYMENT_METHOD_NAME = GATEWAY_DISPLAY_NAME

# First method is the hosted multicoin redirect. All other methods are individual coin/network QR flows.
_INDIVIDUAL_PAYMENT_METHODS = [
    ('cryptopaymate_polygon_usdt', 'polygon/usdt', 'USDT on Polygon'),
    ('cryptopaymate_polygon_usdc', 'polygon/usdc', 'USDC on Polygon'),
    ('cryptopaymate_trc20_usdt', 'trc20/usdt', 'USDT on TRON TRC-20'),
    ('cryptopaymate_erc20_usdt', 'erc20/usdt', 'USDT on Ethereum ERC-20'),
    ('cryptopaymate_erc20_usdc', 'erc20/usdc', 'USDC on Ethereum ERC-20'),
    ('cryptopaymate_base_usdc', 'base/usdc', 'USDC on Base'),
    ('cryptopaymate_base_usdt', 'base/usdt', 'USDT on Base'),
    ('cryptopaymate_bep20_usdt', 'bep20/usdt', 'USDT on BNB Smart Chain BEP-20'),
    ('cryptopaymate_bep20_usdc', 'bep20/usdc', 'USDC on BNB Smart Chain BEP-20'),
    ('cryptopaymate_btc', 'btc', 'Bitcoin'),
    ('cryptopaymate_ltc', 'ltc', 'Litecoin'),
    ('cryptopaymate_doge', 'doge', 'Dogecoin'),
    ('cryptopaymate_bch', 'bch', 'Bitcoin Cash'),
    ('cryptopaymate_eth', 'eth', 'Ethereum'),
    ('cryptopaymate_trx', 'trx', 'TRX'),
    ('cryptopaymate_polygon_pol', 'polygon/pol', 'POL on Polygon'),
    ('cryptopaymate_polygon_weth', 'polygon/weth', 'WETH on Polygon'),
    ('cryptopaymate_base_eth', 'base/eth', 'ETH on Base'),
    ('cryptopaymate_arbitrum_eth', 'arbitrum/eth', 'ETH on Arbitrum'),
    ('cryptopaymate_arbitrum_usdc', 'arbitrum/usdc', 'USDC on Arbitrum'),
    ('cryptopaymate_arbitrum_usdc_e', 'arbitrum/usdc.e', 'USDC.e on Arbitrum'),
    ('cryptopaymate_avax_c_avax', 'avax-c/avax', 'AVAX on Avalanche C-Chain'),
    ('cryptopaymate_avax_c_usdc', 'avax-c/usdc', 'USDC on Avalanche C-Chain'),
    ('cryptopaymate_avax_c_usdt', 'avax-c/usdt', 'USDT on Avalanche C-Chain'),
    ('cryptopaymate_optimism_eth', 'optimism/eth', 'ETH on Optimism'),
    ('cryptopaymate_optimism_usdc', 'optimism/usdc', 'USDC on Optimism'),
    ('cryptopaymate_linea_usdc', 'linea/usdc', 'USDC on Linea'),
    ('cryptopaymate_sol_sol', 'sol/sol', 'SOL on Solana'),
    ('cryptopaymate_sol_usdc', 'sol/usdc', 'USDC on Solana'),
    ('cryptopaymate_sol_usdt', 'sol/usdt', 'USDT on Solana'),
    ('cryptopaymate_arbitrum_arb', 'arbitrum/arb', 'ARB on Arbitrum'),
    ('cryptopaymate_arbitrum_dai', 'arbitrum/dai', 'DAI on Arbitrum'),
    ('cryptopaymate_arbitrum_link', 'arbitrum/link', 'LINK on Arbitrum'),
    ('cryptopaymate_arbitrum_pepe', 'arbitrum/pepe', 'PEPE on Arbitrum'),
    ('cryptopaymate_arbitrum_pyusd', 'arbitrum/pyusd', 'PYUSD on Arbitrum'),
    ('cryptopaymate_arbitrum_usdt0', 'arbitrum/usdt0', 'USDT0 on Arbitrum'),
    ('cryptopaymate_avax_c_usdc_e', 'avax-c/usdc.e', 'USDC.e on Avalanche C-Chain'),
    ('cryptopaymate_avax_c_wavax', 'avax-c/wavax', 'WAVAX on Avalanche C-Chain'),
    ('cryptopaymate_avax_c_weth_e', 'avax-c/weth.e', 'WETH.e on Avalanche C-Chain'),
    ('cryptopaymate_base_cbbtc', 'base/cbbtc', 'cbBTC on Base'),
    ('cryptopaymate_base_dai', 'base/dai', 'DAI on Base'),
    ('cryptopaymate_bep20_1inch', 'bep20/1inch', '1INCH on BNB Smart Chain BEP-20'),
    ('cryptopaymate_bep20_ada', 'bep20/ada', 'ADA on BNB Smart Chain BEP-20'),
    ('cryptopaymate_bep20_bnb', 'bep20/bnb', 'BNB on BNB Smart Chain BEP-20'),
    ('cryptopaymate_bep20_btcb', 'bep20/btcb', 'BTCB on BNB Smart Chain BEP-20'),
    ('cryptopaymate_bep20_cake', 'bep20/cake', 'CAKE on BNB Smart Chain BEP-20'),
    ('cryptopaymate_bep20_dai', 'bep20/dai', 'DAI on BNB Smart Chain BEP-20'),
    ('cryptopaymate_bep20_doge', 'bep20/doge', 'DOGE on BNB Smart Chain BEP-20'),
    ('cryptopaymate_bep20_eth', 'bep20/eth', 'ETH on BNB Smart Chain BEP-20'),
    ('cryptopaymate_bep20_ltc', 'bep20/ltc', 'LTC on BNB Smart Chain BEP-20'),
    ('cryptopaymate_bep20_phpt', 'bep20/phpt', 'PHPT on BNB Smart Chain BEP-20'),
    ('cryptopaymate_bep20_shib', 'bep20/shib', 'SHIB on BNB Smart Chain BEP-20'),
    ('cryptopaymate_bep20_usd1', 'bep20/usd1', 'USD1 on BNB Smart Chain BEP-20'),
    ('cryptopaymate_bep20_xrp', 'bep20/xrp', 'XRP on BNB Smart Chain BEP-20'),
    ('cryptopaymate_erc20_1inch', 'erc20/1inch', '1INCH on Ethereum ERC-20'),
    ('cryptopaymate_erc20_pol', 'erc20/POL', 'POL on Ethereum ERC-20'),
    ('cryptopaymate_erc20_arb', 'erc20/arb', 'ARB on Ethereum ERC-20'),
    ('cryptopaymate_erc20_bnb', 'erc20/bnb', 'BNB on Ethereum ERC-20'),
    ('cryptopaymate_erc20_cbbtc', 'erc20/cbbtc', 'cbBTC on Ethereum ERC-20'),
    ('cryptopaymate_erc20_dai', 'erc20/dai', 'DAI on Ethereum ERC-20'),
    ('cryptopaymate_erc20_link', 'erc20/link', 'LINK on Ethereum ERC-20'),
    ('cryptopaymate_erc20_ondo', 'erc20/ondo', 'ONDO on Ethereum ERC-20'),
    ('cryptopaymate_erc20_pepe', 'erc20/pepe', 'PEPE on Ethereum ERC-20'),
    ('cryptopaymate_erc20_pyusd', 'erc20/pyusd', 'PYUSD on Ethereum ERC-20'),
    ('cryptopaymate_erc20_shib', 'erc20/shib', 'SHIB on Ethereum ERC-20'),
    ('cryptopaymate_erc20_usd1', 'erc20/usd1', 'USD1 on Ethereum ERC-20'),
    ('cryptopaymate_erc20_wxrp', 'erc20/wxrp', 'WXRP on Ethereum ERC-20'),
    ('cryptopaymate_linea_eth', 'linea/eth', 'ETH on Linea'),
    ('cryptopaymate_linea_usdt', 'linea/usdt', 'USDT on Linea'),
    ('cryptopaymate_monad_mon', 'monad/mon', 'MON on Monad'),
    ('cryptopaymate_monad_usdc', 'monad/usdc', 'USDC on Monad'),
    ('cryptopaymate_monad_usdt0', 'monad/usdt0', 'USDT0 on Monad'),
    ('cryptopaymate_optimism_dai', 'optimism/dai', 'DAI on Optimism'),
    ('cryptopaymate_optimism_link', 'optimism/link', 'LINK on Optimism'),
    ('cryptopaymate_optimism_op', 'optimism/op', 'OP on Optimism'),
    ('cryptopaymate_optimism_usdc_e', 'optimism/usdc.e', 'USDC.e on Optimism'),
    ('cryptopaymate_optimism_usdt', 'optimism/usdt', 'USDT on Optimism'),
    ('cryptopaymate_optimism_usdt0', 'optimism/usdt0', 'USDT0 on Optimism'),
    ('cryptopaymate_polygon_avax', 'polygon/avax', 'AVAX on Polygon'),
    ('cryptopaymate_polygon_usdc_e', 'polygon/usdc.e', 'USDC.e on Polygon'),
    ('cryptopaymate_sol_cbbtc', 'sol/cbbtc', 'cbBTC on Solana'),
    ('cryptopaymate_sol_eurc', 'sol/eurc', 'EURC on Solana'),
    ('cryptopaymate_sol_pyusd', 'sol/pyusd', 'PYUSD on Solana'),
    ('cryptopaymate_sol_trump', 'sol/trump', 'TRUMP on Solana'),
    ('cryptopaymate_sol_wbtc', 'sol/wbtc', 'WBTC on Solana'),
    ('cryptopaymate_sol_weth', 'sol/weth', 'WETH on Solana'),
    ('cryptopaymate_trc20_btc', 'trc20/btc', 'BTC on TRON TRC-20'),
    ('cryptopaymate_trc20_inrt', 'trc20/inrt', 'INRT on TRON TRC-20'),
    ('cryptopaymate_trc20_tusd', 'trc20/tusd', 'TUSD on TRON TRC-20'),
    ('cryptopaymate_trc20_usdd', 'trc20/usdd', 'USDD on TRON TRC-20'),
]
PAYMENT_METHODS = [(MULTICOIN_METHOD_CODE, 'multicoin', MULTICOIN_METHOD_NAME)] + _INDIVIDUAL_PAYMENT_METHODS
PAYMENT_METHOD_TICKER_MAP = {code: ticker for code, ticker, label in PAYMENT_METHODS}
PAYMENT_METHOD_CODES = [code for code, ticker, label in PAYMENT_METHODS]

TICKERS = [
    ('polygon/usdt', 'USDT on Polygon'),
    ('polygon/usdc', 'USDC on Polygon'),
    ('trc20/usdt', 'USDT on TRON TRC-20'),
    ('erc20/usdt', 'USDT on Ethereum ERC-20'),
    ('erc20/usdc', 'USDC on Ethereum ERC-20'),
    ('base/usdc', 'USDC on Base'),
    ('base/usdt', 'USDT on Base'),
    ('bep20/usdt', 'USDT on BNB Smart Chain BEP-20'),
    ('bep20/usdc', 'USDC on BNB Smart Chain BEP-20'),
    ('btc', 'Bitcoin'),
    ('ltc', 'Litecoin'),
    ('doge', 'Dogecoin'),
    ('bch', 'Bitcoin Cash'),
    ('eth', 'Ethereum'),
    ('trx', 'TRX'),
    ('polygon/pol', 'POL on Polygon'),
    ('polygon/weth', 'WETH on Polygon'),
    ('base/eth', 'ETH on Base'),
    ('arbitrum/eth', 'ETH on Arbitrum'),
    ('arbitrum/usdc', 'USDC on Arbitrum'),
    ('arbitrum/usdc.e', 'USDC.e on Arbitrum'),
    ('avax-c/avax', 'AVAX on Avalanche C-Chain'),
    ('avax-c/usdc', 'USDC on Avalanche C-Chain'),
    ('avax-c/usdt', 'USDT on Avalanche C-Chain'),
    ('optimism/eth', 'ETH on Optimism'),
    ('optimism/usdc', 'USDC on Optimism'),
    ('linea/usdc', 'USDC on Linea'),
    ('sol/sol', 'SOL on Solana'),
    ('sol/usdc', 'USDC on Solana'),
    ('sol/usdt', 'USDT on Solana'),
    ('arbitrum/arb', 'ARB on Arbitrum'),
    ('arbitrum/dai', 'DAI on Arbitrum'),
    ('arbitrum/link', 'LINK on Arbitrum'),
    ('arbitrum/pepe', 'PEPE on Arbitrum'),
    ('arbitrum/pyusd', 'PYUSD on Arbitrum'),
    ('arbitrum/usdt0', 'USDT0 on Arbitrum'),
    ('avax-c/usdc.e', 'USDC.e on Avalanche C-Chain'),
    ('avax-c/wavax', 'WAVAX on Avalanche C-Chain'),
    ('avax-c/weth.e', 'WETH.e on Avalanche C-Chain'),
    ('base/cbbtc', 'cbBTC on Base'),
    ('base/dai', 'DAI on Base'),
    ('bep20/1inch', '1INCH on BNB Smart Chain BEP-20'),
    ('bep20/ada', 'ADA on BNB Smart Chain BEP-20'),
    ('bep20/bnb', 'BNB on BNB Smart Chain BEP-20'),
    ('bep20/btcb', 'BTCB on BNB Smart Chain BEP-20'),
    ('bep20/cake', 'CAKE on BNB Smart Chain BEP-20'),
    ('bep20/dai', 'DAI on BNB Smart Chain BEP-20'),
    ('bep20/doge', 'DOGE on BNB Smart Chain BEP-20'),
    ('bep20/eth', 'ETH on BNB Smart Chain BEP-20'),
    ('bep20/ltc', 'LTC on BNB Smart Chain BEP-20'),
    ('bep20/phpt', 'PHPT on BNB Smart Chain BEP-20'),
    ('bep20/shib', 'SHIB on BNB Smart Chain BEP-20'),
    ('bep20/usd1', 'USD1 on BNB Smart Chain BEP-20'),
    ('bep20/xrp', 'XRP on BNB Smart Chain BEP-20'),
    ('erc20/1inch', '1INCH on Ethereum ERC-20'),
    ('erc20/POL', 'POL on Ethereum ERC-20'),
    ('erc20/arb', 'ARB on Ethereum ERC-20'),
    ('erc20/bnb', 'BNB on Ethereum ERC-20'),
    ('erc20/cbbtc', 'cbBTC on Ethereum ERC-20'),
    ('erc20/dai', 'DAI on Ethereum ERC-20'),
    ('erc20/link', 'LINK on Ethereum ERC-20'),
    ('erc20/ondo', 'ONDO on Ethereum ERC-20'),
    ('erc20/pepe', 'PEPE on Ethereum ERC-20'),
    ('erc20/pyusd', 'PYUSD on Ethereum ERC-20'),
    ('erc20/shib', 'SHIB on Ethereum ERC-20'),
    ('erc20/usd1', 'USD1 on Ethereum ERC-20'),
    ('erc20/wxrp', 'WXRP on Ethereum ERC-20'),
    ('linea/eth', 'ETH on Linea'),
    ('linea/usdt', 'USDT on Linea'),
    ('monad/mon', 'MON on Monad'),
    ('monad/usdc', 'USDC on Monad'),
    ('monad/usdt0', 'USDT0 on Monad'),
    ('optimism/dai', 'DAI on Optimism'),
    ('optimism/link', 'LINK on Optimism'),
    ('optimism/op', 'OP on Optimism'),
    ('optimism/usdc.e', 'USDC.e on Optimism'),
    ('optimism/usdt', 'USDT on Optimism'),
    ('optimism/usdt0', 'USDT0 on Optimism'),
    ('polygon/avax', 'AVAX on Polygon'),
    ('polygon/usdc.e', 'USDC.e on Polygon'),
    ('sol/cbbtc', 'cbBTC on Solana'),
    ('sol/eurc', 'EURC on Solana'),
    ('sol/pyusd', 'PYUSD on Solana'),
    ('sol/trump', 'TRUMP on Solana'),
    ('sol/wbtc', 'WBTC on Solana'),
    ('sol/weth', 'WETH on Solana'),
    ('trc20/btc', 'BTC on TRON TRC-20'),
    ('trc20/inrt', 'INRT on TRON TRC-20'),
    ('trc20/tusd', 'TUSD on TRON TRC-20'),
    ('trc20/usdd', 'USDD on TRON TRC-20'),
    ('custom', 'Custom ticker'),
]

TICKER_MINIMUMS = {
    'btc': 0.0001064,
    'bch': 0.000665,
    'ltc': 0.00266,
    'doge': 13.3,
    'bep20/bnb': 0.00133,
    'bep20/eth': 0.00133,
    'bep20/usdc': 1.33,
    'bep20/usdt': 1.33,
    'erc20/usdc': 2.66,
    'erc20/usdt': 2.66,
    'erc20/dai': 19.95,
    'erc20/link': 0.8645,
    'polygon/pol': 0.665,
    'polygon/usdc': 0.665,
    'polygon/usdt': 0.665,
    'polygon/weth': 0.000665,
    'base/eth': 0.000399,
    'base/usdc': 3.99,
    'base/usdt': 3.99,
    'arbitrum/eth': 0.000133,
    'arbitrum/usdc': 1.33,
    'arbitrum/usdc.e': 1.33,
    'avax-c/avax': 0.0133,
    'avax-c/usdc': 1.33,
    'avax-c/usdt': 1.33,
    'optimism/eth': 0.000133,
    'optimism/usdc': 1.33,
    'linea/usdc': 1.33,
    'sol/sol': 0.00532,
    'sol/usdc': 1.33,
    'sol/usdt': 1.33,
    'trc20/usdt': 13.3,
    'trx': 13.3,
}

